# Generated by Django 2.0.6 on 2018-06-25 16:24

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRun',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('url', models.URLField(
                    db_index=True,
                    verbose_name='URL')),
                ('callback_url', models.URLField(
                    verbose_name='Callback URL')),
                ('callback_auth_code', models.CharField(
                    max_length=50,
                    verbose_name='callback auth code')),
                ('requested', models.DateTimeField(
                    db_index=True,
                    verbose_name='requested')),
                ('started', models.DateTimeField(
                    blank=True,
                    db_index=True,
                    null=True,
                    verbose_name='started')),
                ('finished', models.DateTimeField(
                    blank=True,
                    db_index=True,
                    null=True,
                    verbose_name='finished')),
                ('dns_results', django.contrib.postgres.fields.ArrayField(
                    base_field=models.GenericIPAddressField(),
                    blank=True,
                    default=list,
                    size=None,
                    verbose_name='DNS results')),
            ],
            options={
                'verbose_name': 'instance run',
                'verbose_name_plural': 'instance runs',
                'ordering': ('requested', 'started', 'finished'),
            },
        ),
        migrations.CreateModel(
            name='InstanceRunResult',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('when', models.DateTimeField(
                    auto_now_add=True)),
                ('pings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('web_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instancerun', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='results',
                    to='measurements.InstanceRun',
                    verbose_name='instance run')),
                ('marvin', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='instances.Marvin',
                    verbose_name='Marvin')),
            ],
            options={
                'verbose_name': 'instance run result',
                'verbose_name_plural': 'instance run results',
            },
        ),
    ]
