# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.6 on 2018-06-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancerun',
            name='callback_auth_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='callback auth code'),
        ),
        migrations.AlterField(
            model_name='instancerun',
            name='callback_url',
            field=models.URLField(blank=True, verbose_name='Callback URL'),
        ),
    ]
