# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-09 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0002_auto_20180626_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancerunresult',
            old_name='pings',
            new_name='ping_response',
        ),
    ]
