# Generated by Django 2.0.7 on 2018-07-17 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0004_remove_instancerun_callback_auth_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRunMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveSmallIntegerField(
                    choices=[(50, 'Critical'), (40, 'Error'), (30, 'Warning'), (20, 'Info'), (10, 'Debug')],
                    verbose_name='severity')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                ('instancerun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                                  to='measurements.InstanceRun', verbose_name='instance run')),
            ],
            options={
                'verbose_name': 'instance run message',
                'verbose_name_plural': 'instance run messages',
                'ordering': ('instancerun', '-severity'),
            },
        ),
    ]
