# Generated by Django 2.0.7 on 2018-07-15 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0002_zaphod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvin',
            old_name='alive',
            new_name='is_alive',
        ),
    ]
