# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0002_zaphod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marvin',
            old_name='alive',
            new_name='is_alive',
        ),
        migrations.AlterField(
            model_name='marvin',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='is alive'),
        ),
        migrations.AlterModelOptions(
            name='marvin',
            options={'ordering': ('-is_alive', 'instance_type', '-last_seen')},
        ),
    ]
