# Generated by Django 2.0.7 on 2018-07-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0003_rename_marvin_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvin',
            name='instance_type',
            field=models.CharField(
                choices=[
                    ('dual-stack', 'Dual-stack'),
                    ('v4only', 'IPv4-only'),
                    ('v6only', 'IPv6-only'),
                    ('nat64', 'IPv6 with NAT64')
                ],
                max_length=10,
                verbose_name='instance type'
            ),
        ),
    ]
